apiVersion: v1
kind: Service
metadata:
#  annotations:
#    auth.istio.io/8089: NONE
#  labels:
#    acme.cert-manager.io/http01-solver: 'true'
 name: acme-http-solver
spec:
#  externalTrafficPolicy: Cluster
#  internalTrafficPolicy: Cluster
 ports:
   - name: http
     port: 8089
     protocol: TCP
     targetPort: 8089
 selector:
   acme.cert-manager.io/http01-solver: 'true'
#  sessionAffinity: None
 type: ClusterIP
#  type: NodePort