apiVersion: v1
kind: Service
metadata:
 name: acme-http-solver
spec:
 ports:
   - name: http
     port: 8089
     protocol: TCP
     targetPort: 8089
 selector:
   acme.cert-manager.io/http01-solver: 'true'
 type: ClusterIP