name: harbor-setup

trigger: none

variables:
  - name: APP_NAME
    value: gonchi # This value was modified by the initial-setup python script
  - name: DOMAIN
    value: tferrari.com # This value was modified by the initial-setup python script
  - name: HARBOR_USER
    value: admin 
  - name: HARBOR_PASSWORD
    value: automate-all-the-things 

    

pool:
  vmImage: 'ubuntu-latest' 
  # If you are using a self-hosted agent, comment out the previous line and uncomment the following three
  # name: <agent-pool-name> # Insert here the name of the agent pool you created
  # demands:
  #   - agent.name -equals <agent-name> # Insert here the name of the agent you created


steps:
- script: | 
    curl -X 'POST' -u $(HARBOR_USER):$(HARBOR_PASSWORD) \
      "https://harbor.$(DOMAIN)/api/v2.0/projects" \
      -H 'accept: application/json' \
      -H 'X-Resource-Name-In-Location: false' \
      -H 'Content-Type: application/json' \
      -d '{
      "project_name": "$(APP_NAME)",
      "metadata": {
        "public": "true",
        "enable_content_trust": "false",
        "enable_content_trust_cosign": "false",
        "prevent_vul": "false",
        "auto_scan": "false"
      }
    }'
  displayName: 'Create Harbor project for $(APP_NAME)'
