name: harbor-setup

trigger: none

# parameters:
#   - name: HARBOR_USER
#     displayName: 'Introduce the user for Harbor'
#     type: string
#   - name: HARBOR_PASSWORD
#     displayName: 'Introduce the password for Harbor'
#     type: string

variables:
  - group: aws-keys
  - name: AWS_REGION
    value: us-east-2  # This value was modified by the initial-setup python script
  - name: APP_NAME
    value: gonchi # This value was modified by the initial-setup python script
    

pool:
  vmImage: 'ubuntu-latest' 
  # If you are using a self-hosted agent, comment out the previous line and uncomment the following three
  # name: <agent-pool-name> # Insert here the name of the agent pool you created
  # demands:
  #   - agent.name -equals <agent-name> # Insert here the name of the agent you created


steps:
# # In this case it's necessary to specify the checkout with the persistCredential options set to true. This will enable us to push the changes to the repo.
- checkout: self
  persistCredentials: true

- script: | 
    mkdir ~/.aws
    echo -e "[default]\naws_access_key_id = $(aws_access_key_id)\naws_secret_access_key = $(aws_secret_access_key)" > ~/.aws/credentials
    echo -e "[default]\nregion = $(AWS_REGION)"> ~/.aws/config 
  displayName: 'Configure AWS Profile'

- task: AWSCLI@1
  displayName: 'Update KubeConfig'
  inputs:
    awsCredentials: 'aws'
    regionName: '$(AWS_REGION)' 
    awsCommand: 'eks'
    awsSubCommand: 'update-kubeconfig'
    awsArguments: '--name $(APP_NAME)-cluster --region $(AWS_REGION)' 

- script: |
    while [[ $(kubectl get -n registry ingress harbor-ingress -o 'jsonpath={.status.loadBalancer.ingress[0].hostname}') == '' ]]; do
      echo "Harbor Ingress is not ready. Checking again in 5 seconds..."
      sleep 5
    done
    kubectl get ingress -n registry harbor-ingress -o=jsonpath="{.status.loadBalancer.ingress[].hostname}{'\n'}" > harbor-endpoint.txt
  displayName: 'Get Harbor Endpoint'

- script: |
    sed -i "s|externalURL:.*|externalURL: http://$(cat harbor-endpoint.txt) # This value was modified by the harbor-setup pipeline|g" helm/infra/harbor/values-custom.yaml    
  displayName: 'Modify harbor helm chart values'
    # sed -i "s|AATT_HARBOR_REGISTRY|$(cat harbor-endpoint.txt)|g" helm/infra/harbor/values-custom.yaml    

- script: |
    sed -i "s|repository:.*|repository: $(cat harbor-endpoint.txt):80/$(APP_NAME)/$(APP_NAME)-backend # This value was modified by the harbor-setup pipeline|g" helm/my-app/backend/values.yaml   
    sed -i "s|repository:.*|repository: $(cat harbor-endpoint.txt):80/$(APP_NAME)/$(APP_NAME)-frontend # This value was modified by the harbor-setup pipeline|g" helm/my-app/frontend/values.yaml   
  displayName: 'Modify $(APP_NAME) helm charts values'
    # sed -i "s|AATT_HARBOR_REGISTRY|$(cat harbor-endpoint.txt)|g" helm/my-app/backend/values.yaml    
    # sed -i "s|AATT_HARBOR_REGISTRY|$(cat harbor-endpoint.txt)|g" helm/my-app/frontend/values.yaml    

- script: |
    sed -i "s|value:.* # This value was modified by the harbor-setup pipeline|value: $(cat harbor-endpoint.txt):80 # This value was modified by the harbor-setup pipeline|g" azure-devops/01-build-and-deploy-backend.yml  
    sed -i "s|value:.* # This value was modified by the harbor-setup pipeline|value: $(cat harbor-endpoint.txt):80 # This value was modified by the harbor-setup pipeline|g" azure-devops/02-build-and-deploy-frontend.yml  
  displayName: 'Modify build & deploy pipelines'
    # sed -i "s|AATT_HARBOR_REGISTRY|$(cat harbor-endpoint.txt)|g" azure-devops/01X-build-and-deploy-backend.yml    
    # sed -i "s|AATT_HARBOR_REGISTRY|$(cat harbor-endpoint.txt)|g" azure-devops/01X-build-and-deploy-frontend.yml    

- script: |
    git pull origin main
    git config --global user.email "AzureDevOps@HarborPipeline.com"
    git config --global user.name "Azure DevOps - Harbor Pipeline"
    git checkout -b main
    git add helm/infra/harbor/values-custom.yaml
    git add helm/my-app/backend/values.yaml
    git add helm/my-app/frontend/values.yaml
    git add azure-devops/01-build-and-deploy-backend.yml
    git add azure-devops/02-build-and-deploy-frontend.yml
    git commit -m "Harbor endpoint URL updated by Azure DevOps"
    git push --set-upstream origin main
  displayName: 'Push changes to GitHub'

# - task: DockerInstaller@0
#   displayName: Install Docker
#   inputs:
#     dockerVersion: '17.09.0-ce'

# - script: | 
#     cat /etc/docker/daemon.json
#   displayName: 'probando'

# - script: | 
#     sudo echo '{ "exec-opts": ["native.cgroupdriver=cgroupfs"], "cgroup-parent": "/actions_job", "insecure-registries" : ["k8s-registry-harborin-3fc40329a9-502641590.us-east-2.elb.amazonaws.com:80"] }' > /etc/docker/daemon.json
#   displayName: 'probando2'

# - task: Docker@2
#   displayName: Build And Push Image
#   inputs:
#     containerRegistry: 'dockerhub'
#     repository: 'k8s-registry-harborin-3fc40329a9-502641590.us-east-2.elb.amazonaws.com:80/my-app/backend:1'
#     command: 'buildAndPush'
#     Dockerfile: 'my-app/backend/Dockerfile'

# - script: | 
#     curl -X 'POST' -u admin:automate-all-the-things \
#       "http://$(cat harbor-endpoint.txt | tr -d '\n')/api/v2.0/projects" \
#       -H 'accept: application/json' \
#       -H 'X-Resource-Name-In-Location: false' \
#       -H 'Content-Type: application/json' \
#       -d '{
#       "project_name": "$(APP_NAME)",
#       "metadata": {
#         "public": "false",
#         "enable_content_trust": "false",
#         "enable_content_trust_cosign": "true",
#         "prevent_vul": "true",
#         "severity": "low",
#         "auto_scan": "true"
#       }
#     }'
#   displayName: 'Create Harbor project for $(APP_NAME)'


- script: | 
    curl -X 'POST' -u admin:automate-all-the-things \
      "http://$(cat harbor-endpoint.txt | tr -d '\n')/api/v2.0/projects" \
      -H 'accept: application/json' \
      -H 'X-Resource-Name-In-Location: false' \
      -H 'Content-Type: application/json' \
      -d '{
      "project_name": "$(APP_NAME)",
      "metadata": {
        "public": "true",
        "enable_content_trust": "false",
        "enable_content_trust_cosign": "false",
        "prevent_vul": "false",
        "auto_scan": "false"
      }
    }'
  displayName: 'Create Harbor project for $(APP_NAME)'

# # We use podman because it allows us to push to instecure (http) registries with the flag "--tls-verify=false"
# - script: | 
#     apt-get -y install podman
#   displayName: 'Install podman'

# - script: | 
#     podman login --username admin --password automate-all-the-things k8s-registry-harborin-3fc40329a9-502641590.us-east-2.elb.amazonaws.com:80 --tls-verify=false
#   displayName: 'Login to registry'

# - script: | 
#     podman image build --tag k8s-registry-harborin-3fc40329a9-502641590.us-east-2.elb.amazonaws.com:80/my-app/backend:1 my-app/backend
#   displayName: 'Build image'

# - script: | 
#     podman image push k8s-registry-harborin-3fc40329a9-502641590.us-east-2.elb.amazonaws.com:80/my-app/backend:1 --tls-verify=false
#   displayName: 'Push image'

# - script: | 
#     docker login --username admin --password automate-all-the-things k8s-registry-harborin-3fc40329a9-502641590.us-east-2.elb.amazonaws.com:80
#   displayName: 'Login to registry'
# - script: | 
#     docker image build --tag k8s-registry-harborin-3fc40329a9-502641590.us-east-2.elb.amazonaws.com:80/my-app/backend:1 my-app/backend
#   displayName: 'Build image'