environment: stage

redis_host: master.gonchi-stage-elascache-rep-group.u0khnz.use2.cache.amazonaws.com # This value was modified by the deploy-infra pipeline

deployment:
  image:
    tag: 1082
  replicas: 1

secret:
  redis_pass: AgCgd4fsD3S1mFjV2tGP8wR3pQSoy+vkl84aw+tSc3VrsoXiAnkezxhU4Qiqu67wEM3XFZDDvrwiKby71bnC3p/IcROKyuHtUj5uaJXIu4sMlF95FUhVTSgH0j1r/XmR4DjD8nRiNApJKBjhFmIx85kcqlPzlj+DbbwijaxG2vAG5/+rY1o15GN98yIM6pFS7yxhArQRruVS6cSIaLKwqC12FylUi8Fqfjt3ikk2w4RM8OYNUJ7kuR6SAm3jfwX+ggRCjLzKR3zu+U+ql3E0wi/5AQTRbIrjtfO1MNJTzahZ5vRnA4vZmVOKee7DevNnpt8iZJ5hKd+JODW7IWOyQU5vYzZEI6wrTqQfGA6ZUu8EmGJhF8gpnvrkSM6vh1SlZaWzIiGHQIhdpd4E4GiFxQfGuE32Pwlbyt0CiNuPlWoA5FyKfm08XYMC+lBksBbtXEV2sprtHIQnx1LhhGq6gw+vL1GAP5KT389KifzCE6vMooFwUAavWXtrPVEqGd2gBRQ1ikPKy8S5Ko6mW3o/1Hl/c2puGgHOjHypo23z63RQStD1L8tlPXNDTA870gz6sRVBH1gvmJ3fDJ312avqpUhSYfM9hIrEpUS4XkWeVuhe5CKbWTxpxCSrRPmra+/WoCNM313DMNRMVEqdE7M9PFyFRE4qDGqp5qblEyNbfWELfQ+LH+htcUtO8MBHh8BRNYHWEXYRZg2pgIuyOgAJeXsha+uhBptqq5TsD4Vlrg== # This value was modified by the sealed-secrets pipeline
