environment: stage

redis_host: master.gonchi-stage-elascache-rep-group.u0khnz.use2.cache.amazonaws.com # This value was modified by the deploy-infra pipeline

deployment:
  image:
    tag: 1082
  replicas: 1

secret:
  redis_pass: AgBXYbigeAfVVEWjO0IxBLgzvDq/sUoDY2O4Ou1V4fBCybcEAiZgZcBx9hMG2PkABX4TY4xspYkZPW01nKgT0JjibW2KpZLR19gj6CXF7cNDMs4eHnXGknYBAP3dIPmloM4t6Kvoa2QMIGE8W9yt662ljAPEwvYQI7S3mPA9QzVdwRuMX35aXeuwFOARcBmEwKCPaaTqqBsw7vA8Mj14ohXnTHfUU1kBFg1rDl4QhdkzuIfqR4ezHG/yXnkFi6ZzEskKuezN9ixJVS6LEv7YSA8Wex+vkw0fEC76H+uxLz8cGm9uDu7LJpFVqCNM4nlUbCcRp3jS1+JDLTh/uXEvjFoK8rBSKgwHJdBSMQ67hafqIvq4epJYxLKTDrZut07W3K5AB8Md5c0wx1jVtEcVBxLdzPcFRNIgHMEjs3iIPw59gueFHDu3JwwB+fKWexJFHBqMByEBg9NL/fhv2Qz+706wTKGc2RWlqDLcH74vxyyBBApIydUso9Ruiqptn7bzcaY5p0mO2l9fWkqilXLHsAAV5J4U99pl7W8XgeGQS6luQiMHqjid8P9TqJY2OVzpt3YmL1WApniG4IQaaGRh82SCW2FcB6qhyOk+RsUMGnIXInCjBe80dznTsnSO38IW6I73hRODkhzcgfG2Le8KPc03tAP3Q+lwxzu7wGlzIg2ntb5Zy89byWG6qJsWO68sIFH65OOK5MIV8I4N4Ig4xodldOZxGo1Rx9jPHLutvA== # This value was modified by the sealed-secrets pipeline
