environment: dev
    
# redis_host: master.gonchi-dev-elascache-rep-group.u0khnz.use2.cache.amazonaws.com # This value was modified by the deploy-infra pipeline
redis_host: database-dev-redis-master

deployment:
  image:  
    tag: 1082
  replicas: 1

secret:
  redis_pass: AgDW/jYw9RhB5JJTWJ6VcijQSnyxOcNSWuziqHL8Vhbeq9fGuwTOPnNnjQlF5ILUdl2KbDpx6EaRyXCt0N/bwEg0Kh/Afb1M32pP0WCWS3ka+YyHWGu3fAS2UOjrAI45y4BK71TjQzM0APZqLlihMiWPm25i9g963pAsPy3utUhyTA0PlwQcLWFrv6BHHhu4pnqyUBhf3aT75WhpxksFg+q7DUfK1kOsZanmGmSabqt8hh8Rz5b+2YHZZnX6++2WCFX63OfnyM5mZfmWzgEoKi+D4GZz+AsWfn52Jl48vdqS9Wb0eOrTqinJCdPmQwxSC5D8UPgmy0P4dBrCg6rTzWoel9XkWQx6DH1CMbnKy0/3DVSq1gogNU681AKQBq2KLthhnFNsFq/hUZON0mAze1vzTl2W07XTkq0xXtPxZk63vB8ZWfyq2HjHRbm6J/TIYLA0MPUShh2ZnQEaYVpqIT5nwOwsSzbBi8ul7rve6uH/6X9bjDhedv0N/7AaeE+uqWlMcvkWkJjW/iFxLg97h2pFyvr2rLJyzR7Xce4vvXvWTQk7FryZkLoiyEJWAVVqoqbEjUo3TWyibJLvbpM8efQuvLQloJx0EQNOJd4OwkUiKc4/KXE3GLlD/oOD6RM/l3WrLxESMVp5UeH9eRytNIqMSYiShYOIYZWz4toWjZHF7E8Xfu6NVrneCCSB3dpT3eIyQZLzt3+1W4uaEhzzGg0os4gLYbUTiAyXH0c= # This value was modified by the sealed-secrets pipeline
