environment: prod

redis_host: master.gonchi-prod-elascache-rep-group.5piid5.use1.cache.amazonaws.com # This value was modified by the deploy-infra pipeline

deployment:
  image:
    tag: 1082
  replicas: 1
    
secret:
  redis_pass: AgAaR8ckggtxglqIjYaH9QsAcR9B0zVuBWOlJ43N0w9fnj6X432UF+T/5ypiTBBkHPnq/FV9Ox9TywyKxbxgVXJGuOxxCs4bTSM+xGx7cbrNqcJH69IWFRLZTxX/5V5ACsuNuu0Vc05Fn+1HZFCBfqMkGNU8MiWbWVzpVXX91skdxp29RLkOn4K40oF8554EUO9sLlmefsafknX0wzNXw42MBrgItyWk9cHkSmJSQ+kGUonKoZhfBkL7+b4JUH8jQCzH69nsobYFFD/TDDc7VvZNoSNIND4QO51uigFOwFM/mkJhbgti65KHoOTaUgb60OxWQWsv7EnISTBCBlUtg+Jq3YBgmIQxWjcGRDsRLEucmAYIIxzFPlkDV76AAVY4FgqJmbeFaRyvD1texekSZNraFuhtedqTRg+8by8N2RckPvTqg6drMjDWf/U6rAGzNGqzDgDxPA/vDfhrR097XwQNwmTOA/FjuP3amk0bf3up3e+mCZ4vlwNHzm3W4QxszjJ+axGfGq+zpZ4dR7eX/V3YtR5cW1i3VVLfPvoeqdsKzhbQU13zyV2nYVEE2+uxXY7Agys/2JBt2yEXQMyX7CmK4yffi/cnLxd6TnpaCTI27w4a57YV1aEWcrWPG33p67M9Paxcb+CFd5+DVB9q9MLmhHRYBRkJB5WZaevrqj12/KxoCYR97kPoVtI0e9iYsRxzcVljcPZae2ACHq9tZbWW8cUWsDNjpnRYhCjU # This value was modified by the sealed-secrets pipeline
