environment: dev
    
# redis_host: master.gonchi-dev-elascache-rep-group.u0khnz.use2.cache.amazonaws.com # This value was modified by the deploy-infra pipeline
redis_host: database-dev-redis-master

deployment:
  image:  
    tag: 1082
  replicas: 1

secret:
  redis_pass: AgAjLNjdsmlttFf1yD2AGW3kPNskwmrN3/eKofTQ+J0MemLGJBzWNWtHYGR0+aENiEWnTvpQCQKBLSMw1aEE6w177CqRZwfACCRsiEZ0yAzY79dug/30yEVlsVXH5Cr2/64DqgpjVF2F62nJOSQ35v1M7slZkws0a/JdegqwQ4Rk7HQK6e3SsXwtEplSVDBLxri0ulIl9ZQVTszIbGsCP/aibnRH7aDO/f8+z/E05ulrlln4smmS8Vhz13dERJyvegOzckzS4trV4dQyLjwN75ygdhfANzaTPwGLzmYwVvNK6UJbzCzZj2kmLVlgoEHvgX6wt2aeujHBP/o4WWsSzGNxvgm/ynBaNV9NgRuHvV+1otFnHyyvvTOMHG+kZEVO80nph0UNLN/iRjui0ZlkDUZg6Gp1Yf+ZuRiRrgJ1WXhTZbGxGGcNRIH8B+TVt9RaX3IjvgB29XieZhnMBnHzDSSOSc8N6i6RdEqLK7GHGV7g9HsnmsbEjYs+PO56tugT2lVu9bJPvTE18JZlvPubgYPgXoFcPU/erWAWmUJKHbkt85Aoc38nLz5ZWofWMG9PTJPRL4byFAvYHmfWL2ocj7mgyjvNZkcV8fi4xPM04dgdDnTZ3rGvxdBXiD/ahdALi55EkaLoOM8QCGxszDo6L9jFrrBUcOG0YklSz9L7HZlLC3EHJqvsnUljLRccEd8qMDHfy4Pj8UvIpkyXUjCHAsZIYUb90BAyXrr+GEc= # This value was modified by the sealed-secrets pipeline
