environment: stage

redis_host: sdfasd # This value was modified by the deploy-infra pipeline

deployment:
  image:
    tag: 1463
  replicas: 1

secret:
  redis_pass: AgBd6nY6HsL0Av5yBltXPdQ35a2Ug624tPUb1IjqeCU9Sz6nB3/uBDdfINYTRTYUk6fHVfP4gANDzR10ZYmub0pBrRB4U5F0V4pf5uTIJaVKqz0OhA+Q+2X6+Z1RlTvbGkJ9ikNLc34i+wZW+gG3RaC3j4vWN826axG6HhVzzc3gceBQalLcsiqW4nm6gy9LwnGsL8GQBMC39QB+pV0+oxpOeiLRsllvaw+ZGELynIlbpqcZ/zLq9k1MhtMq0hwrMIoeYiZl8RL0wuMV/9akpcp/BXogXLRql5flJslS0+VNvcq0HXL4IWr8g4v/+VFNhruCiJoxW14SVof9Ybe48cgAW5TY4py8vTvOcv4m63qX+ouhVPt/mXNjC/PK7TUseq1UCWA50+untBFjIYevcQeJE8hqz3io+RhTthL3TbgWrPHmDv/lTi4WLY4FYms1XfGDRunsMKMrQuwSzVJDDrmma/176MLnCPUe20VbUtGHoJRKGPbm74TyaOGMgzYd9Z22K8eo1MkxyhKYBqEd+ZFKayT9JzsgqGb+ribuG0ZmLZNKdJkTOHX9flyyGqIbJvRaH3abw57yfBpOBuK0ldXo9aW3HuOU5u/Z/2gOjDZCEZgKQU1od0coGultKy9QxEwUD2GVOgWUbSoXGWmE4imnW8r7pRN1z0t6UfS6ikpl38+WiDrGgl8BNjvyHR8h7YSklj96pZsI1eLCVyGeL1HCxqKPf+nzp39WEZwS2iZZ2Af76WXArzyympfmIMrNYYB0 # This value was modified by the sealed-secrets pipeline
