environment: prod

redis_host: master.gonchi-prod-elascache-rep-group.u0khnz.use2.cache.amazonaws.com # This value was modified by the deploy-infra pipeline

deployment:
  image:
    tag: 1082
  replicas: 1
    
secret:
  redis_pass: AgBYxt/8SsN0BITN3dOv2deFtY9ZWHwevLWAmo+eb7BY9cdSCV/3Q8Rd6kkta+ZHC4GdLMx5xnIu4vK1VRZXwiRmNB4UVPA5nrSFUunOlxt7cDQDThch+sSs2S6RUDsXgGqRwG49rNTkz+n6JuFQTYBrx5ExFYWUYbSClwL3aK1dt/ua1HMYFYYXe5DAV/keH8oBMdKd9+GSjFNJMSuxF1QrvHesjB0XkB0KnxyBUNsVYvq2Crf9y9JwxGblIO/7Y3UxO3AKlOpSOhV+LmHH/ykDH/pV7eCJkrA6lHL4fnGsEPJZJT5cMHPfd9Vv3kVUwKC4UWpNKEA9Rovf3TFj1VT4wu5DgYRYYTUKR6A/G/3195dhyTVcDmRPEIqQ1hWpq4PCUMWLMFfdOgeW40VY9rSBuBtqrthnG0GOw7l3qLAAb4J9jNovhuBSY1EwicpOWWMoRc3OUs4GRbAYuJQG1RIuQdkiw2GTJA68G7Pym98jhVinr6y72iqVPFqPzzFyO2P25PbvxzwetjmnZC9gsJhir1oBPqFjK1t/N2BQGcva1Lyfw6c63+niXyiH59xRkDHcuVqrjfCeIFyZxg3N5HZWMKgvdtDWE+I3G4YFojrC58wrosKIbjN2TGs9h1tBbZE/O3Uos3QJ8GlLGTOMQ1R1s3DEFwAV3dEvtQnC6zehNzcksYqj9zomF8uioEQ0FAm+onhSCjuXG3zbPBY351Rx3LNkptrUMlYTve3V # This value was modified by the sealed-secrets pipeline
