environment: prod

redis_host: master.gonchi-prod-elascache-rep-group.u0khnz.use2.cache.amazonaws.com # This value was modified by the deploy-infra pipeline

deployment:
  image:
    tag: 1082
  replicas: 1
    
secret:
  redis_pass: AgCUmWIFy4Euwa0z3NJYfojIRAq5H68lfCMFHg6GaWO8FE6r8H+hHBRhYQY9up+g24v+nWS0UfOCqTE87a34GWZvfOIuWS77XKMDvB8HP/dqbtssLX4R5A209N++Gv1wUkh7RkRqXzgWG2eYCxKOLTykYKSR/x2+WUay+l7ms2xybtC2w6flkVNIkO2rCUb4GUR0C2RFYh0I/+cIjOddRIPOTVI9hjBW/d0T5Ecn0citQ3nwfRXSZWkwO7ENJ2TcM2Q6J8ouq6dWtGUAdZxpy+xzll/TvrcXp/1mgevGwIeWmR73Jfizvhz1Ws3CN/+2MnEfwLNICdvEAsidMNiU9seNgD15XwsIdIb77nFg0H865winVGU+HqUJAUmrATMqhEaecXuDxkeWNyZNIqgnCwtxesK2HgBmzPQCiPcwfWRiU8pNn5K5SCOw+7lhLxYwNmbZekNkb6qcf1h697lODZxC88FKaiOe/wpOnvp6l9afy4t+8iXQa69lNcmSCrDPkFBeqCG/3OuJoI3baHvehtR4K1ROY17+XDErwJekCZRxq9ZgBpwUoTeRrh5yvefLxMShTDKl7kQRUGzIrVSA7q2doENMVcGJAxHFBifcH4IylsUKbn4BtGdkx3Ok8kT71mP3VHcWDnt0buhDBeU/d37G11Y4m7k8JzFEYSkgHRM/KTBcXvjAVZkmqw8HVBTAGTk+wQCO8/mGsYcuV+58tvLeevkNM0eFXB5UEBW1 # This value was modified by the sealed-secrets pipeline
