environment: dev
    
# redis_host: master.gonchi-dev-elascache-rep-group.u0khnz.use2.cache.amazonaws.com # This value was modified by the deploy-infra pipeline
redis_host: database-dev-redis-master

deployment:
  image:  
    tag: 1082
  replicas: 1

secret:
  redis_pass: AgCIRJhuFnE6ryyqrSi7JPH+dc+KWBqYeXCje9RukvI6V6qNX3HEgn3dQeTyOvsk2TFIXVZOvu2LWsx9PZ/fnUH+s+sZJPlQL0N5R7NTAgmg8uKjQLs62Qd7GWLBCoMMwYMjJyHmLclYt10LTIWriNUYayIuPuyL2TbLvr9bxBtCr0JBsemEtO/352oWglfDkASsn0MHDtRzDe6dXB6+lN25i1jdNQ4eAajGsKtnyVW0AK5BzbLh6btS6nzDjBL0KnXkNkLjC158Cgxl7vHovNYbBSVMcfy0y1TX8Wr4QIcPXtFSGdb9h1wQ9qXPB7azC3QwedP8mg3H4ci0JoiK/QoIn0E0zvZjSzV7kOi80rc3HiNxSJ0vOQvQ2aHp4MKXwS/I862dakZ9sSmR+HFpEhLb98WdbcuBskiTmuGk4vF+LLzq71FPKCoDNWlNqJM3uwLC0unnciYAgfV1c6U5BijuxcXZiTL7MtmoxRVMbkohRgGzmmM8s9DwH1pMkqIpm1iGHeC3eOXACkFoO1MTX9+AqtS6MqscimC5uulNFXvT/9Qjt1AXbKVIfP3P/5u/TK7JlWKbthRiSa+Hx0IEchQQM+dSXT1Xgs8ouXsLLXk+9JDBTkUX6Aag5RcIShrr8VOF1H2YVXTHgsT07HypfFUHMUGSufLI2qqStkcvEMoAFd8ID4wuhmxmp+Hrjpl+JfWN9WVD1vOZKrlFIMip4qwNuPw9rSARa5/6dw8= # This value was modified by the sealed-secrets pipeline
