global:
  istioNamespace: service-mesh

service:
  annotations: {    
    # external-dns.alpha.kubernetes.io/hostname: tferrari.com,
    external-dns.alpha.kubernetes.io/hostname: tferrari.com,dev.tferrari.com,stage.tferrari.com
    # external-dns.alpha.kubernetes.io/hostname: dev.tferrari.com, 
    # external-dns.alpha.kubernetes.io/hostname: stage.tferrari.com 
  }

# This creates issues with terraform destroy
# service:
#   annotations: {    
#     service.beta.kubernetes.io/aws-load-balancer-type: nlb # This is to use a Network Load Balancer (NLB) instead of the default Classic/Elastic Load Balancer (ELB). 
#   }
