apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBtULxQ+GIPp9h9oK4Z6JhxaI1Ia4QFsIW8wowUePEOVvW1v7kquaaSnHhcoX5STZEVfCG6DDLiPc4g0aSXOVZ8CCvxGREO6oP5n2woua0ux2k8bbnP0mfdEQ2aZDM6kSNZKDO1qDK88Rfu7Pp7YoQvTsERT0/2MVWZlcJAwCw0u2dTTvWsUpGldYILmMyO/Ss7Vj//O2cFU3GmomXn7xcbHom8yh3C1iXWx3A7hloahVOQebg/4Rz9dtI0HwhrmOXS1JCDc09uCZrqUVEdFe6Ma+JenbxuLwIX6Bh5rcrgX19GbYiQA9j/m2Fe8VdgR0kvU41k82ltp2PQZByOBjoilNmtpMkKSFXOOHOg4BUyLceV+l2aZmLha3eQnQ4hBCLa0q3H57eQLFqvjY7twJr/AUqluSYi3bNCAXvHHTb1Z8Yr/ABU/kCx/z5aqNrCUg9ch9fW1L4Ncvh50rxTF+CZGFgu06ARqn2RDvNlCCgBPR7FjyxezED9X0CI6dGj29JhQXNU7n/BC/trFMYmCJpTeoaIET2lyprIlWkkDqxfJPzrAIAr50i6TvB6uK+G1Z4HeFOZKHwkEst6beba2DIHl3pitWZwbkfrp19rtkzjDvo7QqPkgkDmfTLJh+mCAw7ueXnv7UB2rTOpXECODYXLF5edifgHLGl2GA4I5LUW7xYaSd2Cg+OSMm6UadiKTyaRrO84MunZrCd17t9ncoolLKHctGQFXeIfwEoMm+ZxRm8lCatr9bbJrQ9Nx9mGdFpFhbkzmofvnYHIME7If24/oM7cWD3HINYNWLZzFAAqwB5S+h3likpsoQjnXpjoWOWcRfWVesWPArVbldWRVT3ttHeUR3JX2zlzu2mLuIl5je0DsZZPLGWjN/0m
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials
      namespace: default
    type: kubernetes.io/dockerconfigjson
---
