system: meme-web 

service: backend

port: 3000

deployment:
  labels:
    system: meme-web 
    service: backend
    backstage.io/kubernetes-id: meme-web-backend 
    istio: monitor
  
  image:
    repository: tferrari92/meme-web-backend # This value was modified by the initial-setup python script

vpcId: vpc-0f080e7de9dd6e9ea # This value was modified by the deploy-infra pipeline
subnetId: subnet-0d139226360f90ee8 # This value was modified by the deploy-infra pipeline
# securityGroupId: sg-0b7bab67c05dab563

region: us-east-1 # This value was modified by the initial-setup python script

# This doesn't work in objects of kind Resource. It only works in objects of kind Component.
# elasticache:
#   annotations:
#     backstage.io/kubernetes-id: meme-web-elasticache 