domainFilters:
  - tferrari.com

policy: sync

# aws:
#   minTTL: 60
#   zonesCacheDuration: 60	

  # set_string {
  #   name  = "logLevel"
  #   value = var.external_dns_chart_log_level
  # }

#   set {
#     name  = "sources"
#     value = "{ingress,service}"
#   }

#   set_string {
#     name  = "aws.zoneType"
#     value = "public"
#   }

#   set_string {
#     name  = "aws.region"
#     value = var.aws_region
#   }
# }
