email: tomas.ferrari@sendati.com

# Default user is "admin"
harborAdminPassword: automate-all-the-things

expose:
  # Set how to expose the service. Set the type as "ingress", "clusterIP", "nodePort" or "loadBalancer"
  # and fill the information in the corresponding section
  # type: loadBalancer
  tls:
  #   # Enable TLS or not.
  #   # Delete the "ssl-redirect" annotations in "expose.ingress.annotations" when TLS is disabled and "expose.type" is "ingress"
  #   # Note: if the "expose.type" is "ingress" and TLS is disabled,
  #   # the port must be included in the command when pulling/pushing images.
  #   # Refer to https://github.com/goharbor/harbor/issues/5291 for details.
    # enabled: false

    auto:
      # The common name used to generate the certificate, it's necessary
      # when the type isn't "ingress"
      commonName: harbor.tferrari.com

    secret:
      # secretName: harbor-tls-production
      secretName: harbor-ingress-certificate

  # loadBalancer:
  #   annotations: {
  #     external-dns.alpha.kubernetes.io/hostname: harbor.tferrari.com
  #   }
    
  ingress:
    hosts:
      core: harbor.tferrari.com # This value was modified by the harbor-setup pipeline
    
    # set to the type of ingress controller if it has specific requirements.
    # leave as `default` for most ingress controllers.
    # set to `gce` if using the GCE ingress controller
    # set to `ncp` if using the NCP (NSX-T Container Plugin) ingress controller
    # set to `alb` if using the ALB ingress controller
    # set to `f5-bigip` if using the F5 BIG-IP ingress controller
    controller: alb

    annotations: {
      external-dns.alpha.kubernetes.io/hostname: harbor.tferrari.com, # This value was modified by the harbor-setup pipeline
      # cert-manager.io/cluster-issuer: alb-production-cluster-issuer, 
      cert-manager.io/cluster-issuer: alb-staging-cluster-issuer, 
      ingress.kubernetes.io/force-ssl-redirect: "true",    
      kubernetes.io/ingress.class: alb,
      alb.ingress.kubernetes.io/scheme: internet-facing,
      alb.ingress.kubernetes.io/target-type: ip,
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP,
      alb.ingress.kubernetes.io/healthcheck-port: traffic-port,
      alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15',
      alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5',
      alb.ingress.kubernetes.io/success-codes: '200',
      alb.ingress.kubernetes.io/healthy-threshold-count: '2',
      alb.ingress.kubernetes.io/unhealthy-threshold-count: '2',
    } 



externalURL: https://harbor.tferrari.com # This value was modified by the harbor-setup pipeline

# internalTLS:
#   enabled: true
#   registry:
#     # secret name for registry's tls certs
#     secretName: harbor-ingress

#   portal:
#     # secret name for portal's tls certs
#     secretName: harbor-ingress