# Deploy only in prod
{{- if eq .Values.environment "prod" }} # Only deploy in prod
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: istio-gateway-certificate
  # The Certificate should be created in the same namespace as the istio-ingressgateway deployment.
  namespace: {{ .Values.istioGatewayNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  secretName: istio-gateway-certificate
  # secretName: {{ .Values.appName }}-{{ .Values.environment }}-tferrari-com-crt
  commonName: {{ .Values.host }} # CAMBIA ALGO ESO??
  dnsNames: 
    - {{ .Values.host }}
  issuerRef:
    # Let’s Encrypt has a strict rate limit on certificates issued, so we use the Staging Let’s Encrypt server for testing, and then we switch to the Production Let’s Encrypt server.
    name: istio-staging-cluster-issuer # Comment when switching to Production
    # name: istio-production-cluster-issuer # Uncomment when switching to Production
    # kind: ClusterIssuer
    kind: Issuer
    group: cert-manager.io
{{- end }}


# STAGING
# {{- if eq .Values.environment "prod" }} # Only deploy in prod
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: {{ .Values.appName }}-com
#   namespace: {{ .Values.istioGatewayNamespace }}
#   annotations:
#     argocd.argoproj.io/sync-wave: "2"
# spec:
#   secretName: {{ .Values.appName }}-com-crt
#   duration: 2160h # 90d
#   renewBefore: 360h # 15d
#   isCA: false
#   privateKey:
#     algorithm: RSA
#     encoding: PKCS1
#     size: 2048
#   usages:
#     - server auth
#     - client auth
#   dnsNames:
#     - {{ .Values.host }}
#   issuerRef:
#     name: staging-cluster-issuer
#     kind: ClusterIssuer
#     group: cert-manager.io
# {{- end }}


# PRODUCTION
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: {{ .Values.appName }}-com
#   namespace: {{ .Values.istioGatewayNamespace }}
# spec:
#   secretName: {{ .Values.appName }}-com-crt
#   duration: 2160h # 90d
#   renewBefore: 360h # 15d
#   isCA: false
#   privateKey:
#     algorithm: RSA
#     encoding: PKCS1
#     size: 2048
#   usages:
#     - server auth
#     - client auth
#   dnsNames:
#     - {{ .Values.host }}
#   issuerRef:
#     name: production-cluster-issuer
#     kind: ClusterIssuer
#     group: cert-manager.io