apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials
  namespace: gonchi-dev
spec:
  encryptedData:
    .dockerconfigjson: AgB9H2DxcbdBtMuU6QudrG8udqCA7MKRCWIuoarJkvLpFDxKNycsaxhBdgs7+3dgZ1aWNW6w+EelGixnpqz0H3NdYt/9rcA/OAoftx1m0y8G3aivouR/NoT9XXM5V6TSpkPxmaEVA83JA3SF27XE4xxub8oSTgz5XbcLZ5KfSmegFgZcbn3qMYARN3oT+umrC18zpJ85cBPGTD6Hovj/AJaUQd9qNDeERxZOebr/xtqebye8QWI/r7digaIY3pnLD2TScnxFycE3g/9X26mxy4NL1Xh/b/Gp42wNG5fA3dMmf4k8TiPILSXhlmRULYKa0YHVMn9/04xWTBNEc6ihGVEFJbo+0IZ87DYdK1RS5Tk42zgJ8ZiwOF0g0x5P6BtdlwFXtK8+ljp3rRods2AeeD7WNLJWVxzKcXxR/1+jElVspE5fHi24/t51B6uRUHp9zkTtB/oBcmAFdLQveStzjK0dO2rfyI2JiVEdR97SJuKlgQmEXdQjpPIzglXj5PcpsI6RLgsSCE09Iravgu2egU9idGMlOC2GGOsAY3faQUo4ybEUGSJWN4JoSMKiwjhXrGM3qEViG4I1+VrdOQlaELVIfudT6wgCFnu/fh+/p/y9hbiu+H2NCNR06WvUI70DE7ewGoapJzSAAphaWYWVxPuCZb9atwcmsu0yymW8yDv8yxBk/PMD/XQOSKoAynAbzz0exjpK+9ix2mfAGb7faQUKF+5U72VwqHJ6M8WA4u+49h16Ktzby9gQe2H3RSTWWSniYXafBFK3RSe/bs9T0LgBK/xW0aek7FLrn8frntzyCsS1F3+5hgWkIKA+1apuszJ5j4RDTlE1vh99sAjHSeEt7rOh1c08Mw==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials
      namespace: gonchi-dev
    type: kubernetes.io/dockerconfigjson
---
