apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials-stage
  namespace: gonchi-stage
spec:
  encryptedData:
    .dockerconfigjson: AgBm6aA0AT4KF/uqxrR0zMjvONXJY2jOe3XnauNnluDOYu9DkSOMYrId0zfyqou6LJroWY/i0KPxh2m/dHttSqaXVOOI1i5WWn80bE+X9FVhljhaDwZdjV4Rsz6VF+MllLXZ8DEKo6AIrf6Vey+wCSBq7pfrQ39DTY9AdX4612HTwT9JosEmwca614ijrQFYOMWawJWaqYL9eI+I0K57jCyzezzN1kF8OzRCX8aTPV7wrffsDDZN9bfpc+Sw1X+wbwjQ0kNxJ41WNu1YbCvmnAAD+EdJymjp49xT8bIWBbTEfbppTohY/ndcnpEGPxN81EY+y6a+ZaNJhxG0peirLWdAEmJ7kvfPlWG4PBu9/V7r7D38sUOYFff8Xp70+nroypiBi+keeCEQOWGvNEQzdq/XemMaHiSwQRuYbH5iVqIdmmH4f7cEoH3NORy2WAb+0f7eEWt8MUPSNkfb+s6iBgylaQyj3gowfg8INtaUUVfjQkYtEEufauy4MD9xcKFe8N0U+iyTTh8DwBmJeGzK1QHbbIBNj+dPrmGwiU941vVlIvAIxmQtrRmGPDPpyUaxWm/hTUo82WkzMeA5KxsxfvFVQydRQ/tG8nWBVwK2iLIBq3h8BOiQ45bDW+oeHEGf9zTJlzov2gtSgglNFakWUs3qDax2xPhtootmclkIlyYu4iA0UXZ7keY1Sw3tbrmZE89ZoRHn7TSYydiM5mBTFOEemGTv6Bu0Bs+yvn6qH2KvgbIk2rOFG6XVcC38pHRoENq+CLrTSmZJ1Cxy+e+rQgBbHM0cQkd3KXo3JWRfEbtSHipdwvNbWsuxsohzeHzZ+OHCJTvwpc8P80WrpM/fviS3oZ/7/LxYpg==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials-stage
      namespace: gonchi-stage
    type: kubernetes.io/dockerconfigjson
---
{{- end }}
