apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials
  namespace: gonchi-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAeUDGmSLiNAHeQgfhT03LQS0krI9mYIWCG02L/SFH5ET8pM9z4jhmNPLD84MJ6ae/pWCxzuPXKFROfdvrzg0XTgagvcdiva8+KcdqSYv8tFRyNNmSWdfdja2A2Sl05oTkaTG3EYtJychwzHtTwzfGDlHVAM5J5sf2zTFP7vIEVzJvRTPUEcGeY8PxkGTGY8scaEJclAwtHkvvmZXaT7dZX0ij4xbyUIsuNBmLIMBmziNAJZ0FP7SZsJaeTXf9816sjPE2MT+J1eHi4zInXLnLoreyyhoBLXBYNANNDM7bHbJ+vdYW3VJg/grmRssJZ/h/lM90gHyQCP7/35uyJZ/r0wBhuAfczgNz8ghBIk9CBQikXBKtSCTEI/mJOlaQNwlIuTK4QuOZ7PHh/2x2dM73cRmLEEgobjeD7WZjQMEjIJkK3SjLN0KQjiTf7BOG/Gcd5nT46WXBXk23f65cdSeaCZVPRuqIv8PE5W1eTBo3w9YpIu7Iw38vGKlqpGsTGSJ2AXKfnL23JV4R2oVGr1Pwof20aprG0eqnfw1bqedtI3N3LBOyhhQjM91R9u7eGrQvYJvaQrl1fRF+brpXez6YkauLgCl7OYw3kX+I/1jpFgLyyFDkjQA4ROzfZl9VOyHZU0F6dU2fMTnfnnw3Xtxfrnnv/LfAMp0DDllCIJHvCFyIk4NyHUZdFHfzG0aVRl736jUugiOmSa8z3nuLLZOlkWZjMDBhGCcIs7nscVTMPm9qbEEO7SGcoEjj4rcfY72agNMOyLzxC/JnZdyWk09ibeYl+JEjZLBQjUdmxeArqxnXB2Y0t8A51B4BZxJ960E0L3g8w2bKwhLQTKOFjmZDN/QTMvJFJDA==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials
      namespace: gonchi-dev
    type: kubernetes.io/dockerconfigjson
---
