apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials-stage
  namespace: gonchi-stage
spec:
  encryptedData:
    .dockerconfigjson: AgA4dyJlL9dEwM1H7DA7g1VlvFp/LgL/STrLAH9SNt5nfs+J1BRmiXaZ61DmVKWH4VirqXAx5psnyG/hLPxbl68gc+HWcvUot6a/XjEDg11ZGTAnJM1/SXK+/rWmeT/X0MfngJLHs//IJUkXUee3Vd7C69sD9/6UKe4MIDG7dUbfnMDbn9h03UOF/OyDUsc9S/fon0PZGVosh3S2gKP2FHvqx7AKENXIYiFcYQhV7Tb6M4NN+0qM1588i4RFMWFzFBiJWnYxExBmFmNGM7djGC3omO9dPU2auCSOAQEGkP4NiBRH6ltyFQYB+2nGfYhrDGKHWnfiEJsD+eIsRekWSxwwK8Kmfpjiu63GurfZ2zSS1XpBqP6CFr1uEJjRHZZBgP1bQu95I79CV0eSblVuCqakSLjHHtqeCIL5mw5QEvrM/Q7+g1SbDss9dYWVryjsL8heuajzcKZbnUEkMzRvfAfjz060aREtV6w4uXyFuP0WWMpzq4VikQXLsOfR77NYs9CaRAaz4DPrItGCXS/kVhkBVKc/yAqY9YXrvRJXCh4dNkkSTv4zPFh5yX/4Xc/vY6N9LPzVyDApyQtoHgPKHtcE9lwuK1yFQWM1tW1AZJKAYC7lcwdvFHJUzN1Vob9gazkLS168lHRDuhtHNM2X9T08VmyrLkeuzB4jhKIsFxTB539TsU7aZMaLZABgGGhqHotA3pALj+CiCIOTnRDE95QVvCM91buF8maYkUMMmxlZ3xTwyhs7JTh7iQqNMOJtQFFAnfAjx8tmfoeNMHBV4kolXTQ01sqPPVihrXO3d3ZQ8nAvbptJdmxrxDNmrNlu5Y3TQ8HUE2BhCQwkwzQh0WFjsTjPtFKOmg==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials-stage
      namespace: gonchi-stage
    type: kubernetes.io/dockerconfigjson
---
