apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials-prod
  namespace: gonchi-prod
spec:
  encryptedData:
    .dockerconfigjson: AgBf/e5Txi3dfcHALLea+gRzHtgTFoyw6GJVd6Va8ULFIHF14Jw4pmOc7MK3rJv9slAz4zsAZcD8tmHNnrmlFMCIBX4SVBju7t4TyZuu6jtS/DbgcP++dPIqBzH9mxWRpjeeu5+Tb3oQBcwCtrfAxwHKjaY9NxGsnvVrAykuMZ4PrTJyZfdY4QE+S2L6qmB0kkj47Fn3IiVmk9g2b8axSK1r4hOh9mwKLxOwwDR87WrSOCWNedXhXWZfUSGSuZMoPNiGugAUthdk3XcA+aUMG91AahP+fuuga1tS2oGs+B44GpJPJn+xSn2NZhwDgWgud6YCdJwZbOZSN1H9YkVYUxEbAD3g988XGCVzk7B7wnJlREauKn0XpfrKavyDyAwwiPFH7nalo9rq+pomI4w1soQwuSmNQlwxFxyQakpB3L/8aVxNn2HjYeKXtdGTSRw1aWP7fcFYGNGHMJ83xDnzqe+FSZjwzTHg4TuiqVz2Kq9JJRZDzeYVuD73FoFLB6wgaFduDHSHCovuv5XJgJ5QQh67hYdtPQQ3B3RV78u5bYkF5C0ra95PgK+7VQbgpdNgze08t81cK/za0+SQ0Zdr6sre2S24t3bCRLYPNVp4E77RxnFs9iHG82QrH/KxLteKarGWwfKs9YdhR1kAp2SxI0Ylk/dUCpn18cIYDWgM3KVGohZOcka0Tp/Dq40UAW8yiiFlZfdrmUKLjOdYO3uqxu+j7Ka6DtYMbKucmK14+jEM/RK2THagWhwvH6ZbZFuzsEySil681pnMdeRROz9Aj/RM5Ia5FGMzdy2lDq0pwkFoXk3VM+VJ052tO9ShhtljrbAz0VVA/nFjITAhrG5VK7kqreGSShZhqA==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials-prod
      namespace: gonchi-prod
    type: kubernetes.io/dockerconfigjson
---
