apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials
  namespace: gonchi-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBfves+FmNrOZEXwbT8pajgQsIhITmzXnEpsLKZgs34ByerJ5z8WERY3ZfMTCmGbkctQUq3mnCs7J/tOytKW4MIKFWk4JuWX+Y1FQrz6RfvfvmgVzWHctL8sV3yLqlccHN+Nz0r9EF+xVMIdNZfVSOvh0F8JjGtT/PebZP2qtGEyuiVbjZ68BmMGgvy07R4yYohALnC8hDZABEpfPWO5yZidFTh4FU2sbProesMYsNIB4NVedjX7KyVMW/Li5pBce/1wkWG6YtrugokOsu8l+b+ohEOEEfnsKRfrLRBp046ulqJblA00cgLwhsJv0c4ubA9cwGVsXnSCsYNTZvkVbIrSMwt9Y1XRW5F/NdIBmMjPT3jdjc1DlRXlImFyAoXcl/m05Tc5rvGNp2NNHZERO+dgijn5KBNQm+REUZbyi6fMQlRVF/BzEl7+4R5GBYXqKLMf71SPPB7mfm5DhfebmW4RfcSuUB9J5OiPU5OpjezGhEziudNI3s2qzFK2uZ16DyRmp8d8/IX0FeSAvfYcg71jMiMOOK6HzN1i+bC1/yuLfESLwzi7pofnP9vlFwh94fD+8UXDAH4v7YlCeDH6Lyo3bvrapW3qN90NtF3ucr91u/GIO77gWX86tSfmt+RdDFXcYc/cYOvqqFjoQL+wrtBPiiyzaTq17C1cMgOmPlee7ZjsjfAmh9r1kKNwprb8NPFlxTVx6nZnUHLi6a5X4fQLh5rRAmS2UfqV4v5/IQEiKeja/eruSSB32X2VD6zdaT0MFuD1+nZh2Fdx76Sl8BOlGh2kafN6M4nqezbMXE0iWtH+3t/+gtluaFicHtutJDR+7Lr7tRJDJymIkcJQUsU7f9wpg/Y5Q==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials
      namespace: gonchi-dev
    type: kubernetes.io/dockerconfigjson
---
