apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials
  namespace: {{ .Values.appName }}-{{ .Values.environment }}
spec:
  encryptedData:
    .dockerconfigjson: AgCPAu/YrvQA/5B69C2cc/I2JuQANZT/kAcpJWopsx11yGoaWFT3LygWIK3OO40uBCKOi4EbvGmIoX5Kj9J2Cbg/Ns0kzTVUG9Ml1pNinH6EPIyh75uzPfRymDwrVhLah9sWFGmpPwFI7xQrQd2F4DkxiJ941sJRTW0lihIotPQKiQBjkvk0PFIPWZCsqV6RrM1RFLI1UaqzGK7TG8/FKPVMqXgsXqelhLpQb6HZL5pHNw+yS0rzqzl+EI78ziswxZ8eV1FI8yU4eGti2KfevojBc1SNpY6I62f6+7vclzb+xzs2lwwaUHg14BuVf4wN0cJ/9ZkRmmusqtm6MXlGAfPgvUny8wv03bRNu8o6RID11s8cbtfGzQWx3/jCkhvbM+jz12wyzeE5a1uat5IZvj/kfIbEgkrL0LITBPFP0dSuOH6TLm186JFE6J6cGJbGYeP1zXEERCuXHOibM+yvhfUdkZ0biq8PMA86yhjUHG9rmuhMdpACfdgVJb1byfhBqYwwVD7amr1qVXpPdN7Xx0jDAygj/gAZOBu2frha4P0QLPA/9h5AIfZN5vxnjKXonlh+veDB/wmRPUu6LzEswVf3vIEUcaPQb7zY5YqO4OKMSuF52BVh4SGaf92ry9VHcEFLlJfqUkxPeofcyFNW8CWmTQQZTnW+214m91pWBdNMQVj0RzWt+KFeVXXm6AwbU5i5vgyWIQwWUvg7bFsDDxtGuQ1EIaYkmtbQeh6aeqbfNc/6Y+A/seX09OpE22x1egtAwD6sbcVof18R6PQcBXJnvrfk2mdX0AUy/eI9YFQL4RHpNN0eKKM4RPpOwE8kabXwMcpXxR4hDx4dC1+ftaTxrcOu/f+sbg==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials
      namespace: {{ .Values.appName }}-{{ .Values.environment }}
    type: kubernetes.io/dockerconfigjson
---
