apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials-dev
  namespace: gonchi-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCTkaIaNKtf4X5GZPQTUpHiWh1/SDpU20DJcWTc7pkK1y2JK/SfJIXq0afGpuAq4t5ygOjMBmjH0gCSsd2hLgPWNlUxaBNlIrb9gedrCe7t865FOzGjNWPwnN1LGGYh4MEJsmHraXltms96vtdAhHhnnClzQ6Jk2+5CdsQkM41uiLYyZPzU7gB7QhBkpy8SxPMXXHZaQJiyb8D9UTFmYJo38Ngq17yWcP7erzY8mueZW1oLXlPbs5PHHWnB2QZ2AhGSwzDEf//0o3LggRmtgCMPN5RhTME6yaDfTubDBZIU+ay+0j/jTUQO3m4VXUKSYpAN0mbzAVte0TEk2mcZ6A3bYSCbQJzTP3w2MKZUVIFzQJ2l/MQAbJ55KW5cQTZEa4AaitSqgBdOoOuqCa0rDHW+sW3wANc9HgyzKxa/GvkFgphMzJ+As1FWs0170PHVzLt4G1WMb8j57RGGznod7uXbKHhZm2sXvQk2qpEcFBbvEcHFhonMnHk58TwzWpwDuKXDVgUD49rC/CdxKZ78Jsrh6KC0jJt7nDW4ZpMbX0WPiJfMhoC+gwNww/7EAiNoL4Z9uNDqwx9kq6mup4kKXDxTg+xaJYy5I36VjkNX/4nJkHphIVgyKfKlwlkpYakwWnRanUfEeBEyEjmEiDQ5Uvq3OAHR/he2QEgaBjlG1/MIu1Kbw8sW/fT6b/JesGHz0G1Us6zI51SLJSouumhD7eEhWueq50e+Vax3nzFOpteDR3sC/IHfk7axEJBwldC+CoOW8fUspcibAa2qH7vy+hGs9f4g5whSvDIvoNzxImoD1A8gkBEIw1MEG3gNCdRRSvLo9iLRtdr+i4Ng/cPwMTnbZOZgWzaGWA==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials-dev
      namespace: gonchi-dev
    type: kubernetes.io/dockerconfigjson
---
