apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials-prod
  namespace: gonchi-prod
spec:
  encryptedData:
    .dockerconfigjson: AgC2vlJo3N60cYNAIMIlMrHRYoWVZaInTubqGWj5ryFvDsCqNF6TDGjHeGS38QdDlKzJItn8Bahh7uReASLT9xlLGEatICHYWc7CScgGsIeopUHx6qdW4nBEyRinSUfZ1mRATbAc2njJ430cUCHmBFqPS9BFZvWUJvmBe3UxUGztBions8j05Qq1kpxWVWpgbHDzDHihEY7pbVZ0+vMGX+Y5Ayzte5JoiT+i1zz9mDi8b1PjBdiIjsWMNDdmWD9Mb6SWIefPVZV/ZDlQMbYDbFXbF+onchhCf+nwgAo/5YmSdx8zhjBloaxzDMY389+/2WlmEvBZCHcVy+UCDj3389X5dKh8iv1dtXhk3iWU6bYN2X5uBscK70effJLN39Y5BaojVZL7cJlOGQ8vvIM7CPKzoaT0TF3bsbsKbQEzI+baRlHHKXxky51YTNqc0sRLsZxzm819xeVEBLyzoNc1ZttTMdqZ2L/KDvxE4+SKDzgZfE8f1Rm2PrUvpFNy9UvSG/zijIlFb9vWPiViipQQNtUMDkId6FcruS8pbaCzz7QU5/uLSYRkWotdVUJ8tDanmwUgipzx6E6jmyd1+4WJUGx+ZtfNVJXeC4dv1ALXdIB6tEznO5bZaSqGE/ioHP5+iibL9hFIO89wV3VMSkA7WC9+4kxtj8YZpk8H4OFjnXIWQHPINLH/GKeZErUT1ndaSpQg0KuXl2zlmq0mFVde/S0ZcEvdRShSZ1M2mkLeX6mgQWWpp33RxgYo+4Ea3jJstI84fk1b8X1UwsBmV/n8PAA0YGOWus9mhlk/WlFMP3nz2swyBapX+gMI3SF5PyW/BOZeHnVkPbv5BHjwCdlrD33KujbHZUkUqw==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials-prod
      namespace: gonchi-prod
    type: kubernetes.io/dockerconfigjson
---
{{- end }}
