apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials
  namespace: gonchi-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCWrlHV+aFgeh2LWCTy5W8kM2lxHgIRA8goZVcE2WJvPu4Dv1oaIhU20BYGHpecZNYS4eYEdysQYJ7iFU5gHnh21PpesqG3bc16B5zu44yshvq/pMM6NHJZyUX4XyHSDzkCIVZamDh9KppPbisQE9EKAb1x/ctD8tg1nljKe/i8OwEpk375HAB30yhwNz9Ooqv8acx9qBtnODFZYNkn0XGdjFbpDdrmM1XmW4x86l5jFxjx+DbYvN2LhL6YZeVtbV2suVI9xCgfSXSXKDRymDTfQKDmCSSmduQTyWAI3WC5C3UzlXc9+PtbWPz8nM/tOfpwUP2XOwGZv7ozu3btxaSEnDhXRAyx4AAgZ5rZvANoF/HldmnQAwPxgWZEVMnLQCtO8J2psHvayeghtAdC/1W+WDcmO8qhhhArmR0eDm/TDCcpX4q9q5w7YNnwegPLhstFOC0/RXxoEXJwXwmFBZqMsj21MR8dK8b/saRWekPxKRsBJWMCz90YL3ZLDQRFbU51Q7aDRI2ceLWaAeoKGiW4xJbLlJVUXH2SHGVMGP1uHghTdq1nZIHIeEY4GY3AKhoxada+6nEe7jMKNTw2scAvtt+z6WO6fForFQE3I/ynYqKtKXhIdB1G14wBgYIzz8Mm5gMnSp4nZ1WypUj2z2qLujMvgv7EC4LlESjoIjoxzADe166ikoj/yjr3lLCQkSOx/6oVRuvI4XxfeixFu5tK/VhLfnlM9k9ceFuLEOtVarZaoXdM5FVGjvR6QoNknuUbk6KGWpV9Xyyv5UQcEAicf3Yxe8Lp4lg9VjX9mfRrpPKoh2EYHPyYMfFA93BBSHPd/b1J8B31fBVVYwcoDSSzQlewfvY+AVu3C0tookD8q0XquMPdpGR1LDJw
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials
      namespace: gonchi-dev
    type: kubernetes.io/dockerconfigjson
---
