apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials-dev
  namespace: gonchi-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCOxMBNsxiZvEWwDi8SNmFumlEFP3Unlau++SvIBRiSDbkf1gEVW0pa25t7clMIXM13ppT0rXnBMMAK8sxLL/sZWs80PITU6/KCdZSqqll9NX9ZXU166fGlbbFhq5iyjfXolxKQ8o5P7dnqeGOMvk2CDpNE5JKqgrwzn4niEpVZ16LxBLOc2wsmtSt+oEGO245dCADERk9BwZXbFa8opCH1jsPn6nro/RQ1GqVnBaQYKLEINk7hSw6fMdz5rGFE7ASeWR18M7rGZqp9Jhr105U8J5bMQEhSIIuFCVJEjCqPwkJX2m5zHnieYgV09r3AH0mVm2U92V9AdYI8PEw/1p0P5U3vqaJlKU7CnTqYwjBOFHp1R865c4u1MOcJoUm8/wAcDBnCpllrbQ2nghweaXrlbvee3Q4XX3UguAVX4bfw0ave2uy5EhYg0liOs1hpZ9xa+KPgYjgIeI5gxiDcQ64dNNP2iqXYL1i/GhEANFSnW6XoWxig4varxmZJbajeyGK5ZnlYa6s+cif52btdHzCdJI56ptShvmi1aOOS5tlXK1atLoEopCyOFk1nGI3lWy/KyDiwOEYn7+SXGWiy84wKl42g9EyYBEqJ6KLai7SfPK8huzxXFk4sf+PklIVyDH0PJnE6GTmFHm0+5mQqigNuGTTp6subJcZyfh9FgHIt8k8Ax38E6A/AXJYU/fLkJ0U7B4oM9Y7vBqGU/1ZpEWDpzT8kLUX82MZ8roL2W8ifZuazWcnVlvsnnHZQlXsV1mg7bsMCiU8qZRpkGn9AmtAJeYNGh4+B8U56UTz1bAeXOHpF/8kAyCOVT0Xju62pJkRnIvT9uk8sNdlNp+GzbDahG/HXuLM/uw==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials-dev
      namespace: gonchi-dev
    type: kubernetes.io/dockerconfigjson
---
