apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials-stage
  namespace: gonchi-stage
spec:
  encryptedData:
    .dockerconfigjson: AgCzRbAXURgl0eNPWKcb78VH1+C3qB7LnCyGCbSN6Z8Xi+pJfzQ6WUTru9O/Si4qpJTPreFD+lVytTy9KgbnwVWz/qoCqBuDafE03RIFRlxdCjgWIEvLirOCqAGNIbuu9L4OZx7H67HcgFDdcXxFvZJjJEeev4PiLqloZ6XL/lmZu1q3+kVopbzJXzs4xE3ngaoeUGuQZFogyQyKRV7/Kk06rIniAz7JPiJUokHBInLwoMmHac6snqFKecoU6tKlc0gTcmLqdOA2vqjTsjc7Iq1Q1rcxp99K7pB4diBknOyNmlvkeu291/YL5VieeQu3dy29R9gLMm1r+B8pefusXdC0YVisO0Z5UVUyzDxaR9+5GUWPRQ8LBnX9znB8YmbSkSrHdShL0VkNNECEFONr+8CTDU9euQsUdyRiE18CBStk+0cbFHkCdV+7rvom7CbqfgoThMPo8e/9QqT169TgwWfNofsUUOGVvWq2TqTBjBK4PGnDs4Zm/nnipglpbqwvTySusbxkd+T5MJMPhnbd0hZK4kIOq6O+xoyFpPPjRKydN7ZdKkj4X4WtrSNhCrgtueulDEWIsyD5HrI8aDkkYYOTRttkpSwkBVAuyNZV/0MaN4OGNNryScoYZifNMw9Lgq9x/XarC/JDegy1GsFUlIPtGyPimHhHQRF7y4kziTLw4NFe28AWX+niPUDcNJR1LN6V7P1KvZrVGsFbMpgCAjipV/94BTujyQQTWHTaFezXuubdDB+PfmoXdD0r1XVvnKcSKFYABvI7dAjbd4TaDUbfOW3f3Sy19wGguaHuxe4mXnrw6LVjYHpayO21v9wKv2+WysE6TN4s+NqQoC8EIq9ZQCHglUMubg==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials-stage
      namespace: gonchi-stage
    type: kubernetes.io/dockerconfigjson
---
