apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials-prod
  namespace: gonchi-prod
spec:
  encryptedData:
    .dockerconfigjson: AgCHXzZKBIBvpp/6trvCZO4qeoyXUl5bQIDn7c+zGfZQ+IwrvD/OTubL2KLbUiNsy2UYkLja4OZ5echfKEsmGjmdMYh4oor2XPuEW+PFh/5H318J4xngpL7Ji5RLOl4kul12pZUl/ersIl+gpHzXaUfJozhWXxXM+az2zVH6DPJCXzjaF64R/QY26AmKAceyAlsVh3FuTdMpDEP2rZEJxKwhJ+jBWlMQQicv9GmwDEyR4TbMU/f7DS7i0ZFH44YBROPW6Jypm/3+kVOhdT5pD84GdsoLI+nGesYNNHYFVc0A5dWiFEIjgFpXhOGmGSr02z6B+334W2hDQtXmuG0Aj9Mog3B3Yf5mrujXcqU+nlTwoeah3U2mTz6YdLEsOjzmf49DjhaBU+tdjIpMkQdSd0TsiVf2LSmOEDOqApHvWgS/7MotcNwSKrnoOy37H+Qhy5nXfnOKcbqUL/1t/FORvtWB5V0Jnmh6Eo3qshcVi/R6GICwzKniaJCCV1Dx6E2ku03ZDizDkDee562NkF4JRemn+OP8NoIkYud31rNkf2j5xmcb5QX60S1U5JEaDNTZpeTV/ws/A1lNEZxJIgH3VFhUfMztGgOdAWKr42ijHt4RfRKdZ5BeVBs2lTSlfhmazG7TRsRMTZ/8xRyQ8cu13QaKibmcj3gMlpPeJOHfbdTFBX33r1knDn9cCfdy0PKfREHPfLDmd0VtgIrVGB2EtmZXss9ssM3k9Nv3Q1ReYKFsJHa4+woP54y7T/qkCA3icmCAIbjEQ4xos0pdapryEg1P5xkvSyqzeZPbi3wMnZM/aOlM/DPK1+xQs7FOSXqYkHq0p0wic6KEltLeKxeT4HwsMBrXc7FbTQ==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials-prod
      namespace: gonchi-prod
    type: kubernetes.io/dockerconfigjson
---
