apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials
  namespace: gonchi-prod
spec:
  encryptedData:
    .dockerconfigjson: AgDPRkJfnUVPui4ECip1RYJDkMkTA5gLgvpS4bX3CLt4o9VWGwxCoFU108cVLuRpZqTN16mWAyqjbPinMrJ4gGL1jW+V4z2IPEJl35UWJL1dTs+Pf5aqJWMEQoJdnxe5zpcDIu5ZB6TrrCm+RINoYb9SBnZpq5IDE61WzIUt8NgDyx8oDtkxfxf0Fexh/qBvTa5nGvW8OYBvzixJrlziCOO6OHYLCOgtRcutwJkvV0AfSuT+26KWWkMrHja8npnLuB0uxerl7ga/GnwL+gQRC4mOS1cWK5GNjjEoVbpjuGSHbDnmtfdscFSt+TazODoiXIR4cKkqmVa6oza3nZB3XUw+vORbnR843PGiBlpl1EWsfRhhtNOjr57GE6KmmUgQOAYo1Zf4ljInu/s7sguQ9pR0qDEZiweUfTWCsDzbftRJwjX2AjKmB/lDLDx8Bp0BJxEXPV5sO8klz+pIzuNc12dL8tOATACXb3Xr/eD3Irt8/gzXNAdrVPIpD4V7FRRDtBzMgNaMfD+saZdMpyi/XbUJO8c9ubjo662eI7etKQE56I8ELOh5vtQXc6p+P6ISxuAMUOZGFVld9kd3VhAmCFAwk81mKLBES0E22gkh+55QoQsjG/+J3sLcTpO10u9cFFEYImJ3y6nQswNCbKl87LG/raVo/u8aBN9hu9tdnK5PFrFVJRhriR3FHYSqH3eACsnMG+jYRQQzDCBm6x3pI0myBYvAiBuMQcvptQLeqixtc8s0v60pbweCdbp80rIdazrVdblcicnSR0oLHsIt/o35gM5YCChqlhaZJ7bXEWWZtkxfAWLGBoVaUqPwXjWs/DLn+iex4YCh/nR3Reb8tr/DS+Uv6x6Yzg==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials
      namespace: gonchi-prod
    type: kubernetes.io/dockerconfigjson
---
