apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-credentials
  namespace: gonchi-stage
spec:
  encryptedData:
    .dockerconfigjson: AgBoK9yIGO7vyGQy7XdNUU+1iGn6a5imepJCsQEFpu4HwI2ytQcoVXbYweDyj5B1XmwR/5rtOvZE4ItTuVoiEo0+jKpwfX2LZXjBeMTESrmR8jOjxAwTD7bvfzdBLw5RKGsJdTNUYK2itK2oxVX4vrsUywnwr8g5eaaTEiCfJeK/J8yGJzLjcjzpC6GA1st58cGT5pCaBUAlC5OMQxqzMU0DB4tmKWqkmX5MwggaAs3Lq7xFTkn0ohFwy6cY1a8wXbkQ6EAm5IOAbrcQV/v2OlMaK+WKm1bW3HmI/vSOtgJRuEfBb+UWtVYQ1LUBqqm4RFX8Q2Hdofq8qOq1A85GekQnwQLOz4CwgF0dC68rMk5PQQ2qTgep06Ig2ZIfuCL2rxyUO5llIiznGqUnVlra5f2dV67sGADoYE6utfOjuq90LtgqTNQP/6vifgdXZzuhG0Fhep5dGA+f2xGyMx4Gw9cLZjUdm2XnF9gQ9Px8dm5ujmB8jVb4uosItmVRd8S4JBWgVl+y8/DZPkmY78sUbCjz7njxK+59Hwhtu+XO9qb1GbJiYTVqe/rivOeHM76tk2dvl7Yvu24EmJa2YJGnOXMyPZG644Jzu0T4dx61P+unhbFtLeJHLzUOETGkZLzcj7FViNSNhkpBGikuOg+XmV5Mt+FfwxSr3e/dteFwve1wgfux0Q0w0HkxhnepCmXClmolz8wUXr5RYKI3RshaTq8vVl6KdJoxMTCMbnVpzsR0v+0JimTPFVkAEll1xUkyORMdwuQwdAIUyDnXCZ4N1neH2/c2kBR5zZW8PrB6LEwHvlqYWjCDk6qqRaLquE7m/aKnDPLKakwE9Y5inUHNvU9PJ3vEX+Cyxw==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-credentials
      namespace: gonchi-stage
    type: kubernetes.io/dockerconfigjson
---
