# apiVersion: bitnami.com/v1alpha1
# kind: SealedSecret
# metadata:
#   creationTimestamp: null
#   name: harbor-credentials
#   namespace: gonchi-dev
# spec:
#   encryptedData:
#     .dockerconfigjson: AgBsST8xbKiR9El1elzyVM2qdz8p1VWXnhQInECziak0zCk+//EUKv3EvB35v+HQgX9pgpnwPbeG/6Sf4IfY129J0sqpz2IiLCoPccY0mZwzVEeqtJ+z1LMlUCCSi1aBxdnFIOcVuuLhQGAxYxBJ1+IArTpgiYUV6iSSWfj4IPVZoAPdLws0FIFJSJfjJH+Zm2agEXfEpYXtqM3IlP8T8EPRuymUJXBzFPz5v44ATj/zbjbiObTc0SvLKJ46ubphHmUoltmV89Oobtod+PPAGp+Dmm31yNHTN4P4t6FW0shz7je3W8oBWjnDvo6uvZp1u3BdEhg/oTqyAOWWRuXk/dWfMMbEoFSTpmh+ucuHWItIR0t6+pTlvvAPs7F4uLnbW5B2M/2PlQfcRMMinPRllHSVb5z0LHVlJ+hMylsZsCGQWjJUXu17ShtrOd3LhLX+kMMsu4nK2TO3Ym0Gy1fnwkpic1XeIkjyZFo4jPxKDvZwdYzHmr5frJhl2vojoGUL80EsUdQyV6oof10NHWxMcwsMJ+pkW+Kv9jZQxRQjjbA1s63EoshvQret3djsum56ZtTvJ8fqE0DoU935CUH8npky0IXzRV4DMwB9SIkTFI3KFyo0YKtYHLDVj7xnjNPv4oVZN/+vFcElgFI8/sDv69t/9icTBi7ahoMNdbMnKlDsqo+fSG8kVqWUkuQzBQdGRiZ4PLCOz/dYLWeImHx1/M8QMvGZT8U1FPAwebydZvN13psudNcO5+RaEIbeYvjyKtIRr34LWXjzffHBxGjZOxDp3m4PmvailDXs0BZ2SwlvfnILeK6LRr9b/vWTARA8smePHV2rNXnVwRD/DEoQOi5AfRYe7V9fUR0vN62R6lpZZph9XRrRaaNAm8m/q91r2iZxQ3qsxxCQlFct8nwBuQcjivIC9vwgEDh84RfWsN5AEtyo/iAxHNU0p6VW3f2AGzzf0aecNb5flDBy5cLV2oJYHP4H5IDrsm6hwQ==
#   template:
#     metadata:
#       creationTimestamp: null
#       name: harbor-credentials
#       namespace: gonchi-dev
#     type: kubernetes.io/dockerconfigjson
# ---
